export const posts = [
  {
    slug: "fig-1502-pressure-rating-guide",
    title: "FIG 1502 explained: pressure ratings, applications, and selection",
    excerpt: "A practical guide to FIG 1502 connections, 10,000 PSI working pressure, and the questions to answer before selecting high-pressure flow iron.",
    category: "Equipment Guides",
    date: "2026-10-05",
    updated: "2026-10-05",
    readTime: "7 min read",
    featured: true,
    keywords: ["FIG 1502", "10,000 PSI flow iron", "high pressure union", "well service equipment"],
    answer: "FIG 1502 is a high-pressure union connection commonly used in well service and stimulation applications. Selection should account for working pressure, service temperature, fluid compatibility, end connections, inspection status, and the complete pressure envelope of the assembled system.",
    sections: [
      { heading: "What is a FIG 1502 connection?", paragraphs: ["FIG 1502 refers to a union configuration widely used to connect high-pressure flowline equipment. Its compact profile and field-friendly make-up support fast rig-up where space and time matter.", "The figure number identifies the union design, not a complete guarantee that every component is suitable for every job. The manufacturer, material class, seal configuration, temperature, service environment, and current inspection condition still matter."] },
      { heading: "Understanding the pressure rating", paragraphs: ["Many FIG 1502 components are associated with a 10,000 PSI cold working pressure, but crews should verify the stamped rating and documentation for each individual component. The lowest-rated component determines the safe working limit of the assembled line.", "Pressure ratings can be affected by temperature and service conditions. Never infer a component rating from color, appearance, or connection style alone."] },
      { heading: "A practical selection checklist", bullets: ["Confirm maximum anticipated working and test pressure.", "Match nominal size, union figure, and male/female orientation.", "Confirm fluid, gas, sour-service, and temperature compatibility.", "Review inspection status, traceability, and visible condition.", "Check the assembled system for mixed ratings or incompatible components."] },
      { heading: "Where Sterling can help", paragraphs: ["Sterling organizes available equipment by drawing number, connection, configuration, and quantity. That gives buyers and field teams a clear starting point for confirming fit before a quote or dispatch."] },
    ],
    faqs: [
      { q: "Is every FIG 1502 component rated to 10,000 PSI?", a: "No. Always verify the rating marked on the specific component and its supporting documentation. System working pressure is limited by its lowest-rated component." },
      { q: "Can different manufacturers’ unions be mixed?", a: "Compatibility should never be assumed. Confirm dimensional, material, seal, and service compatibility with qualified technical personnel before assembly." },
      { q: "What details should I include in an RFQ?", a: "Include nominal size, figure number, working pressure, end orientation, length or style, service conditions, required quantity, and any inspection or documentation requirements." },
    ],
  },
  {
    slug: "how-to-select-high-pressure-plug-valve",
    title: "How to select a high-pressure plug valve for well service",
    excerpt: "The core specifications that matter when sourcing a plug valve for high-pressure well service, from pressure class to end connections.",
    category: "Buyer Resources",
    date: "2026-09-28",
    updated: "2026-10-05",
    readTime: "6 min read",
    featured: false,
    keywords: ["high pressure plug valve", "well service plug valve", "FIG 1502 plug valve"],
    answer: "Select a high-pressure plug valve by confirming maximum working pressure, nominal size, union figure and orientation, media and temperature compatibility, operating method, inspection status, and documentation requirements.",
    sections: [
      { heading: "Start with the full operating envelope", paragraphs: ["A useful valve specification starts with more than nominal size. Document the maximum working pressure, expected temperature range, media, flow direction requirements, cycling frequency, and any sour-service or material constraints."] },
      { heading: "Confirm the connections", paragraphs: ["Connection details must match the rest of the pressure-control system. Record union figure, size, and male or female orientation. Avoid relying on a general description such as “two-inch valve” because several connection families may share the same nominal size."] },
      { heading: "Review operation and maintainability", bullets: ["Confirm the required operating method and available clearance.", "Verify seal and trim suitability for the intended media.", "Ask for traceability and current inspection information.", "Plan isolation, depressurization, and maintenance around the site procedure."] },
      { heading: "Make the RFQ specific", paragraphs: ["A precise RFQ reduces clarification cycles. Use the drawing number when one is available and include every application constraint that affects safe configuration."] },
    ],
    faqs: [
      { q: "What is the first specification to confirm?", a: "Confirm the maximum working pressure and ensure the valve’s documented rating meets the complete application envelope." },
      { q: "Why does end orientation matter?", a: "Male and female union ends determine how the valve fits into the line. The wrong orientation can delay rig-up or require additional components." },
    ],
  },
  {
    slug: "swivel-joint-style-10-vs-style-50",
    title: "Style 10 vs. Style 50 swivel joints: what changes in the field?",
    excerpt: "A straightforward comparison of two common swivel-joint arrangements and how line geometry influences selection.",
    category: "Field Notes",
    date: "2026-09-18",
    updated: "2026-10-05",
    readTime: "5 min read",
    featured: false,
    keywords: ["Style 10 swivel joint", "Style 50 swivel joint", "FIG 1502 swivel joint"],
    answer: "Style 10 and Style 50 swivel joints use different elbow and swivel arrangements to solve different routing needs. Selection depends on required movement, line geometry, connection orientation, pressure rating, and site clearances.",
    sections: [
      { heading: "Why swivel style matters", paragraphs: ["A swivel joint is selected for the path the flowline must follow and the movement the assembly must accommodate. Style is shorthand for an arrangement, but a complete specification also includes size, figure, end orientation, pressure rating, material, and service condition."] },
      { heading: "Style 10", paragraphs: ["Style 10 configurations are commonly considered where a compact change in direction and rotational adjustment support the planned line route. Confirm the exact manufacturer arrangement rather than relying on style number alone."] },
      { heading: "Style 50", paragraphs: ["Style 50 arrangements provide a different geometry for routing and movement. The best choice is the one that aligns naturally with the equipment layout without creating unintended loading or clearance problems."] },
      { heading: "Before the equipment leaves the yard", bullets: ["Lay out the planned route and identify required planes of movement.", "Confirm all union orientations and ratings.", "Inspect swivel movement and current certification status.", "Verify support, restraint, and site-specific operating procedures."] },
    ],
    faqs: [
      { q: "Can I select a swivel joint by style number alone?", a: "No. Also confirm size, figure, pressure rating, end orientation, material, service environment, and the specific manufacturer’s configuration." },
      { q: "Does a swivel joint remove the need for line support?", a: "No. Flowlines still require appropriate support, restraint, inspection, and operation under the governing site procedure." },
    ],
  },
  {
    slug: "high-pressure-flowline-rfq-checklist",
    title: "High-pressure flowline RFQ checklist",
    excerpt: "The information suppliers need to quote plug valves, union pipe, and swivel joints accurately the first time.",
    category: "Buyer Resources",
    date: "2026-09-08",
    updated: "2026-10-05",
    readTime: "4 min read",
    featured: false,
    keywords: ["flowline RFQ", "flow iron quote", "wellhead equipment supplier"],
    answer: "A complete high-pressure flowline RFQ should state item type, quantity, drawing or part number, nominal size, union figure, working pressure, end orientation, length or style, service conditions, inspection and documentation requirements, and required delivery date.",
    sections: [
      { heading: "The minimum information", bullets: ["Equipment name and required quantity.", "Drawing number or part number, if known.", "Nominal size and union figure.", "Working pressure and test requirements.", "Male/female end orientation.", "Length, style, or operating configuration.", "Media, temperature, and special service requirements.", "Inspection, certification, and delivery requirements."] },
      { heading: "Why drawing numbers save time", paragraphs: ["Drawing numbers provide a traceable reference for the intended configuration. They reduce ambiguity where several components have similar descriptions but different geometry, revision, or end arrangement."] },
      { heading: "Confirm availability separately", paragraphs: ["Inventory is a point-in-time view. Ask the supplier to confirm available quantity, condition, documentation, and delivery timing when the quote is issued."] },
    ],
    faqs: [
      { q: "Should an RFQ include the requested delivery date?", a: "Yes. A required-on-site date helps the supplier confirm whether current stock, inspection timing, and logistics can support the job." },
      { q: "Is a product description enough?", a: "A description is useful, but drawing numbers and detailed connection specifications reduce the chance of quoting the wrong configuration." },
    ],
  },
];

export const categories = ["All", ...new Set(posts.map((post) => post.category))];
export const getPost = (slug) => posts.find((post) => post.slug === slug);
